### PR TITLE
Flexible and Effienct Blocksize and Loopdim

### LINKED ISSUE #618: Flexible Block size which depends on GPU
in gpusim, we use fixed block-size (ex: `1024` for most of single-qubit and double-qubit gate-apply, `512` for triple-qubit and quad-qubit dense-matrix-gate-aplly).

In most of GPU, the fixed-value efficiently works, but it sometimes failes.
For example, `block=512` in `quad_qubit_dense_matrix_gate_gpu` doesn't work for H100.
This is probably because H100 can assign many registers per one thread and registers in a block cannot afford with `block=512` when assigning maximum number of registers.

We can get appropriate (maximizing potential occupancy) block-size dynamically using `cudaOccupancyMaxPotentialBlockSize`.

### PR DESCRIPTION
**Pull request by KowerKoint**
close #618 

As I mentioned in the Issue, using `cudaOccupancyMaxPotentialBlockSize` to determine block size does not lost a performance and resolve errors because of insufficient registers in H100.

In addition, I found setting `loop_dim = dim / max(0, n/2-2)` does good at performance of reduction functions.
This PR also apply the observation.

### CODE REVIEW

**Review by ikanago — APPROVED** [review]
Thank you for measurements and implementation! LGTM
I have checked code focusing on util.cu and util.cuh.
But I'm not familiar with GPU very much, we need to ask another reviewer maybe.

**Comment by forest1040** [comment]
I have checked with my NVIDIA GeForce RTX 3070 Ti and CUDA12.4 and the test shows an error.

```
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3070 Ti     Off |   00000000:01:00.0  On |                  N/A |
|  0%   39C    P8             14W /  290W |     489MiB /   8192MiB |     14%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
```

I did the following:
```
$ USE_GPU=Yes USE_TEST=Yes ./script/build_gcc.sh
$ USE_GPU=Yes pip install .
$ USE_GPU=Yes make test -C build -j$(nproc)
```

This is Error Message.
```
Error: /root/qulacs/src/gpusim/memory_ops.cu:160, code: 700, reason: an illegal memory access was encountered
```

**Comment by keichi** [comment]
Hi, I was able to reproduce the same crash on my RTX 3060. Below is an output from compute sanitizer, indicating an out-of-bounds access in the `init_rnd` kernel.

```
========= COMPUTE-SANITIZER
Running main() from /home/keichi/Projects/qulacs/build/_deps/googletest_fetch-src/googletest/src/gtest_main.cc
[==========] Running 85 tests from 7 test suites.
[----------] Global test environment set-up.
[----------] 7 tests from CircuitTest
[ RUN      ] CircuitTest.CircuitBasic
[       OK ] CircuitTest.CircuitBasic (167 ms)
[ RUN      ] CircuitTest.CircuitOptimize
[       OK ] CircuitTest.CircuitOptimize (86 ms)
[ RUN      ] CircuitTest.RandomCircuitOptimize
[       OK ] CircuitTest.RandomCircuitOptimize (37 ms)
[ RUN      ] CircuitTest.RandomCircuitOptimizeLarge
[       OK ] CircuitTest.RandomCircuitOptimizeLarge (39 ms)
[ RUN      ] CircuitTest.SuzukiTrotterExpansion
[       OK ] CircuitTest.SuzukiTrotterExpansion (58 ms)
[ RUN      ] CircuitTest.RotateDiagonalObservable
[       OK ] CircuitTest.RotateDiagonalObservable (3 ms)
[ RUN      ] CircuitTest.SpecialGatesToString
[       OK ] CircuitTest.SpecialGatesToString (0 ms)
[----------] 7 tests from CircuitTest (394 ms total)

[----------] 4 tests from CompatTest
[ RUN      ] CompatTest.ApplyRandomOrderUnitary
========= Invalid __global__ write of size 8 bytes
=========     at init_rnd(curandStateXORWOW *, unsigned int)+0x120
=========     by thread (544,0,0) in block (42,0,0)
=========     Address 0x7f4a65600600 is out of bounds
=========     and is 1,537 bytes after the nearest allocation at 0x7f4a65480000 of size 1,572,864 bytes
=========     Saved host backtrace up to driver entry point at kernel launch time
=========     Host Frame: [0x3344e0]
=========                in /lib/x86_64-linux-gnu/libcuda.so.1
=========     Host Frame:libcudart_static_4d8b33a106dceb3c07a56e26de61f2d53bb62a68 [0x2c973e]
=========                in /home/keichi/Projects/qulacs/bin/gpusim_test
=========     Host Frame:cudaLaunchKernel [0x32c38e]
=========                in /home/keichi/Projects/qulacs/bin/gpusim_test
=========     Host Frame:__device_stub__Z8init_rndP17curandStateXORWOWj(curandStateXORWOW*, unsigned int) [0x2a8aa9]
=========                in /home/keichi/Projects/qulacs/bin/gpusim_test
=========     Host Frame:initialize_Haar_random_state_with_seed_host(void*, unsigned long long, unsigned int, void*, unsigned int) [0x2a90be]
=========                in /home/keichi/Projects/qulacs/bin/gpusim_test
=========     Host Frame:CompatTest_ApplyRandomOrderUnitary_Test::TestBody() [0xfebae]
=========                in /home/keichi/Projects/qulacs/bin/gpusim_test
=========     Host Frame:void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) [0x2843d1]
=========                in /home/keichi/Projects/qulacs/bin/gpusim_test
=========     Host Frame:testing::Test::Run() [clone .part.0] [0x26fbf5]
=========                in /home/keichi/Projects/qulacs/bin/gpusim_test
=========     Host Frame:testing::TestInfo::Run() [0x270382]
=========                in /home/keichi/Projects/qulacs/bin/gpusim_test
=========     Host Frame:testing::TestSuite::Run() [clone .part.0] [0x270c13]
=========                in /home/keichi/Projects/qulacs/bin/gpusim_test
=========     Host Frame:testing::internal::UnitTestImpl::RunAllTests() [0x279014]
=========                in /home/keichi/Projects/qulacs/bin/gpusim_test
=========     Host Frame:testing::UnitTest::Run() [0x270565]
=========                in /home/keichi/Projects/qulacs/bin/gpusim_test
=========     Host Frame:main [0xc3c24]
=========                in /home/keichi/Projects/qulacs/bin/gpusim_test
=========     Host Frame:__libc_start_call_main in ../sysdeps/nptl/libc_start_call_main.h:58 [0x29d90]
=========                in /lib/x86_64-linux-gnu/libc.so.6
=========     Host Frame:__libc_start_main in ../csu/libc-start.c:379 [0x29e40]
=========                in /lib/x86_64-linux-gnu/libc.so.6
=========     Host Frame:_start [0xc4f65]
=========                in /home/keichi/Projects/qulacs/bin/gpusim_test
```

https://github.com/qulacs/qulacs/blob/f7a401162d696b98b77efa19d4506bc20292224c/src/gpusim/memory_ops.cu#L93-L97

I think we need to check if `tid < dim`?

**Comment by KowerKoint** [comment]
Thank you for finding the failure. I fixed.
@forest1040 Could you run test again?

**Comment by forest1040** [comment]
Thank you! LGTM!

**Pull request merged**
