### PR TITLE
Bugfix and add some features for Observable and PauliOperator

### PR DESCRIPTION
**Pull request by hal0taso**
# Update

## [Bugfix] Fix parse for openfermion text
- Bug description
This bug is reported in issue #51 by @TenninYan .

When we passed string of hamiltonian whose coefficient is 0 or its real value is 0 to `Observable::create_observable_from_openfermion_text`, the kernel crashes. 

- Reason
The method accept only a format like `(~~ + ~~j) [~ ~]` in parsing procedure.

- Update
I modified parsing process of `Observable::create_observable_from_openfermion_text`, `Observable::create_observable_from_openfermion_file` and `Observable::create_split_observable`.

## [Feature] Making PauliOperator class availalble to use some limited operation for non hermitian operators
In the previous version, `PauliOperator` class takes only real value as coefficients (it's same as `Observable` class). This changes make possible to take complex value as coefficients, and compute expected value, transition amplitude of non hermitian operator.

**The type of return value of `get_expected_value` and `get_transition_amplitude` is always complex (regardless of whether Observable or PauliOperator is hermitian or not)**

If function for rotation of non hermitian PauliOperator or Observable was called, it outputs error that it is not implemented yet.

### Example 1:
```python3
from qulacs.observable import create_observable_from_openfermion_text
from openfermion.ops import FermionOperator
from openfermion.transforms import jordan_wigner

jw_hamiltonian = jordan_wigner(FermionOperator('0^ 1', 1))
print(jw_hamiltonian)

qulacs_hamiltonian = create_observable_from_openfermion_text(str(jw_hamiltonian))

term_count = qulacs_hamiltonian.get_term_count()
print(term_count)

for i in range(term_count):
    pauli = qulacs_hamiltonian.get_term(i)
    print(pauli)
    print(pauli.get_coef())
    print(pauli.get_index_list())
    print(pauli.get_pauli_id_list())

jw = jordan_wigner(FermionOperator('0^ 0^ 0 0', 1))
print(jw)
qulacs_hamiltonian = create_observable_from_openfermion_text(str(jw))
```
This code outputs 
```
(0.25+0j) [X0 X1] +
0.25j [X0 Y1] +
-0.25j [Y0 X1] +
(0.25+0j) [Y0 Y1]
4
<qulacs.PauliOperator object at 0x10ac85030>
(0.25+0j)
[0, 1]
[1, 1]
<qulacs.PauliOperator object at 0x10ac85538>
0.25j
[0, 1]
[1, 2]
<qulacs.PauliOperator object at 0x10ac85030>
-0.25j
[0, 1]
[2, 1]
<qulacs.PauliOperator object at 0x10ac85538>
(0.25+0j)
[0, 1]
[2, 2]
0
```
### Example 2: 
```python3
import qulacs
from qulacs.observable import create_observable_from_openfermion_text
from openfermion.ops import FermionOperator
from openfermion.transforms import jordan_wigner

jw_hamiltonian = jordan_wigner(FermionOperator('0^ 1', 1))
print(jw_hamiltonian)
qulacs_hamiltonian = create_observable_from_openfermion_text(str(jw_hamiltonian))
bra = qulacs.QuantumState(2)
ket = qulacs.QuantumState(2)
bra.set_computational_basis(1)
ket.set_computational_basis(2)

res = qulacs_hamiltonian.get_transition_amplitude(bra, ket)
print(res)
```
the outputs is complex number
```
(0.25+0j) [X0 X1] +
0.25j [X0 Y1] +
-0.25j [Y0 X1] +
(0.25+0j) [Y0 Y1]
(1+0j)
```
### Example 3:
If you try to rotate with non hermitian operator as this code, 
```python
import qulacs
from qulacs.observable import create_observable_from_openfermion_text
from openfermion.ops import FermionOperator
from openfermion.transforms import jordan_wigner

jw_hamiltonian = jordan_wigner(FermionOperator('0^ 1', 1))

circuit = qulacs.QuantumCircuit(2)
qulacs_hamiltonian = create_observable_from_openfermion_text(str(jw_hamiltonian))
circuit.add_observable_rotation_gate(qulacs_hamiltonian, 0.1, 100)
```
you will get outputs as following
```
Error: QuantumCircuit::add_observable_rotation_gate(const Observable& observable, double angle, UINT num_repeats): not impremented for non hermitian
...
```

### CODE REVIEW

**Comment by TenninYan** [comment]
complexにするとscipy optimize使えなくなるのか・・・
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-14-011520ae37dc> in <module>()
      1 method = "BFGS"
      2 options = {"disp": True, "maxiter": 50, "gtol": 1e-6}
----> 3 opt = minimize(cost, init_theta_list, method = method)

~/.pyenv/versions/anaconda3-5.1.0/envs/fermi/lib/python3.6/site-packages/scipy/optimize/_minimize.py in minimize(fun, x0, args, method, jac, hess, hessp, bounds, constraints, tol, callback, options)
    595         return _minimize_cg(fun, x0, args, jac, callback, **options)
    596     elif meth == 'bfgs':
--> 597         return _minimize_bfgs(fun, x0, args, jac, callback, **options)
    598     elif meth == 'newton-cg':
    599         return _minimize_newtoncg(fun, x0, args, jac, hess, hessp, callback,

~/.pyenv/versions/anaconda3-5.1.0/envs/fermi/lib/python3.6/site-packages/scipy/optimize/optimize.py in _minimize_bfgs(fun, x0, args, jac, callback, gtol, norm, eps, maxiter, disp, return_all, **unknown_options)
    961     else:
    962         grad_calls, myfprime = wrap_function(fprime, args)
--> 963     gfk = myfprime(x0)
    964     k = 0
    965     N = len(x0)

~/.pyenv/versions/anaconda3-5.1.0/envs/fermi/lib/python3.6/site-packages/scipy/optimize/optimize.py in function_wrapper(*wrapper_args)
    291     def function_wrapper(*wrapper_args):
    292         ncalls[0] += 1
--> 293         return function(*(wrapper_args + args))
    294 
    295     return ncalls, function_wrapper

~/.pyenv/versions/anaconda3-5.1.0/envs/fermi/lib/python3.6/site-packages/scipy/optimize/optimize.py in approx_fprime(xk, f, epsilon, *args)
    721 
    722     """
--> 723     return _approx_fprime_helper(xk, f, epsilon, args=args)
    724 
    725 

~/.pyenv/versions/anaconda3-5.1.0/envs/fermi/lib/python3.6/site-packages/scipy/optimize/optimize.py in _approx_fprime_helper(xk, f, epsilon, args, f0)
    661         ei[k] = 1.0
    662         d = epsilon * ei
--> 663         grad[k] = (f(*((xk + d,) + args)) - f0) / d[k]
    664         ei[k] = 0.0
    665     return grad

TypeError: can't convert complex to float
```

**Comment by hal0taso** [comment]
@TenninYan `get_expected_value`の返り値をcomplexにしたため, 最小化する関数 (ここだと `cost` )の返り値を, 実数値を返すように変更する必要があります.

**Comment by kosukemtr** [comment]
エルミートな operator に対しては real で返すようにしたほうが使い勝手がいいと思いました。Observable クラスに ifHermitian みたいな属性を付与してそういうふうにすることはできませんか？

**Comment by hal0taso** [comment]
@kosukemtr 
わかりました 🙆 
修正します

**Comment by kosukemtr** [comment]
python に出すのが難しそうということでしたのでとりあえずなしでも構いません。

**Comment by hal0taso** [comment]
I modified `Observable` class and implemented two class: `GeneralQuantumOperator` and `RealValuedQuantumOperator`.

`GeneralQuantumOperator` is a class for generalized operator allowing complex coefficients (i.e., non hermitian) . This class has some basic member functions.

`RealValuedQuantumOperator` inherits `GeneralQuantumOperator`, and it can be used as same as previous `Observable` class. This class allows to add only hermitian operators. If non hermitian operator was added, it will output error messages. 

I also aliased `RealValuedQuantumOperator` to `Observable`, so you can use same programs as you used before. 

Sample code is here:
```python3
import qulacs
from qulacs.observable import create_observable_from_openfermion_text
from qulacs.generalQuantumOperator import create_general_quantum_operator_from_openfermion_text
from openfermion.ops import FermionOperator
from openfermion.transforms import jordan_wigner

jw_hamiltonian = jordan_wigner(FermionOperator('0^ 1', 1))
print(jw_hamiltonian)

qulacs_observable = create_observable_from_openfermion_text(str(jw_hamiltonian))
qulacs_general_quantum_operator = create_general_quantum_operator_from_openfermion_text(str(jw_hamiltonian))

obs_term_count = qulacs_observable.get_term_count()
gqop_term_count = qulacs_general_quantum_operator.get_term_count()
print("when observable: ", obs_term_count)
for i in range(obs_term_count):
    pauli = qulacs_observable.get_term(i)
    print(pauli.get_coef())
    print(pauli.get_index_list())
    print(pauli.get_pauli_id_list())

print("when general_quantum_operator: ", gqop_term_count)
for i in range(gqop_term_count):
    pauli = qulacs_general_quantum_operator.get_term(i)
    print(pauli.get_coef())
    print(pauli.get_index_list())
    print(pauli.get_pauli_id_list())
```
it outputs
```
(0.25+0j) [X0 X1] +
0.25j [X0 Y1] +
-0.25j [Y0 X1] +
(0.25+0j) [Y0 Y1]
Error: RealValuedQuantumOperator::add_operator(const PauliOperator* mpt): PauliOperator must be Hermitian.
Error: RealValuedQuantumOperator::add_operator(const PauliOperator* mpt): PauliOperator must be Hermitian.
[observable]  2
(0.25+0j)
[0, 1]
[1, 1]
(0.25+0j)
[0, 1]
[2, 2]
[general_quantum_operator]  4
(0.25+0j)
[0, 1]
[1, 1]
0.25j
[0, 1]
[1, 2]
-0.25j
[0, 1]
[2, 1]
(0.25+0j)
[0, 1]
[2, 2]
```

**Comment by corryvrequan** [comment]
LGTM

**Pull request merged**
