### PR TITLE
554 add tutorial quantum circuit

### PR DESCRIPTION
**Pull request by Glacialte**
Added some functions such as copy, merge_circuit to the tutorial sections Quantum Circuit and 量子回路.

### CODE REVIEW

**Review by herring101 — APPROVED** [review]
👍

**Review by KowerKoint — COMMENTED** [review]
You should add comment lines in English guide as well as ones you added in Japanese guide.

**Comment by Glacialte** [comment]
OK, I added English guide

**Review by KowerKoint — APPROVED** [review]
Thank you!

**Review by forest1040 — APPROVED** [review]
👍

**Pull request merged**
