### PR TITLE
Enable mfpmath option only if x86

### PR DESCRIPTION
**Pull request by r-imai-quantum**
related issue: https://github.com/qulacs/qulacs/issues/481

- Updated CMakeLists.txt
- I ran `pip install .[dev]` in my chromebook (aarch64) then I saw the installation can be done without errors.

### CODE REVIEW

**Review by KowerKoint — COMMENTED** [review]
Thank you. I confirm the issue and the solution by using [amd64v8:ubuntu](https://hub.docker.com/r/arm64v8/ubuntu/) image run on Apple Silicon.

I wonder if the problem also check `"AMD64"` like line 20, but I found that `${CMAKE_HOST_SYSTEM_PROCESSOR}` (which is got from `uname -m`) cannot be the value `"AMD64"`, so it's OK.
ref: https://stackoverflow.com/questions/45125516/possible-values-for-uname-m

**Review by KowerKoint — APPROVED** [review]

**Review by forest1040 — APPROVED** [review]
The AMD64 is integrated with the x86-64, so this looks fine.
I thought it might be AMD64 if I used MSVC as a compiler, but after all Windows builds with gcc -8, so I think that's fine.

**Review by ikanago — APPROVED** [review]
I have checked `mfpmath=both` is disabled on aarch64 and the build finished without problem.  Thank you for your fix!

**Comment by r-imai-quantum** [comment]
Thank you all for your comments and approval!

**Pull request merged**
