### PR TITLE
Rewrite get matrix function in cpp from py

### PR DESCRIPTION
**Pull request by gandalfr-KY**
The get_matrix function has been added to the general_quantum_operator class method.
It was returning an error when qubit was 1, which has been fixed.

### CODE REVIEW

**Review by KowerKoint — COMMENTED** [review]
Thank you for nice implementation!
Could you add some tests?

**Comment by gandalfr-KY** [comment]
Added a test. There was also a problem with zero elements remaining in the calculation results, which has been corrected.

**Review by KowerKoint — APPROVED** [review]
Thank you!

**Review by forest1040 — APPROVED** [review]
👍

**Pull request merged**
